name: Trigger auto deployment for flask-hello

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/flask-hello-AutoDeployTrigger-6350fff5-2585-4263-9247-0efa48965a3c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FLASKHELLO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FLASKHELLO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FLASKHELLO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.FLASKHELLO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FLASKHELLO_REGISTRY_PASSWORD }}
          containerAppName: flask-hello
          resourceGroup: flaskbasic93da
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


